### ISSUE TITLE
Serializing doesn't warn about duplicate editor ids (Version 0.7.0)

### ISSUE THREAD

**Issue by ra2phoenix** [Mutagen-Modding/Spriggit#31] opened 2023-10-10 05:16 UTC
Use case: My modlist renames a spell tome from both Odin and Apocalypse to "SpellTomeConjuration5ConjureKyrkrim".  I noticed it was missing when doing a round trip delta patch.  On checking the yaml files, there is one entry in Book/ and it's the Apocalypse one.  The Odin one was never serialized and the log doesn't show any errors when processing.  Should it behave like CK and append DUPLICATE etc rather than destroying data?

Only oddity that stands out was during first serialize:
2023-10-09 21:49:54.109 -07:00 [INF] Getting target framework directory for C:\Users\ra2ph\AppData\Local\Temp\e3thvthc.v4e\Mutagen.Bethesda.Serialization.SourceGenerator.1.3.0
2023-10-09 21:49:54.109 -07:00 [INF] Could not locate framework directory

**Comment by Noggog** [comment] 2023-10-10 05:20
Mutagen doesn't really deal in EditorIDs much at all during these processes.   If you think something is getting dropped, it wouldn't be on account of duplicate EditorIDs, I wouldn't think.

Are you able to upload your patch that you're serializing?

**Comment by ra2phoenix** [comment] 2023-10-11 06:23
It uses it for the filenames, though? I solved the issue by changing the editor id to add "DUP" and now I have two .yaml files as expected:
<myfile.esp>/Books/
SpellTomeConjuration5ConjureKyrkrim.yaml
SpellTomeConjuration5ConjureKyrkrimDUP.yaml

Even if the content inside is vastly different, it can't occupy the same name, so only one gets written.  Usually not a problem for most patches, cause people prefix stuff all wildly differently in their mods, but my list is trying to standardize things a bit and so tripped over this one file per edid limit.

My patch has quite a lot of masters, but I could try to create one just using Apoc/Odin that demonstrates this record.

**Comment by Noggog** [comment] 2023-10-12 07:59
Ah true, it would collide in the filespace.   I think first base would be having Spriggit at least error out about it.   After that we can figure out if it's Spriggit's place to try to rename things

**Comment by ra2phoenix** [comment] 2023-10-13 00:29
I'd be totally cool with it erroring out, then I know I need to go address things in my patches where necessary.

**Comment by JasonJShuler** [comment] 2024-04-25 15:17
This is sort of a huge deal, and I'm opposed to simply erroring out. Duplicate editor ids happen, and especially during development you may leave some in there. _REGULARLY_

editorids are not a key at all - you can change them or remove them entirely and it has no impact - the formid is the only key.

I lost like, 18 chairs meticulously placed because this nerfed them all into a single record and I didn't notice. This issue alone is a deal breaker - this tool cannot possibly be used for source control if it can't reproduce the .esm, nor can it serialize a temporary working state. Kind of a huge letdown really - not sure how I'm going to get everything back in place with the xrefs to lights and whatnot

**Comment by Noggog** [comment] 2024-04-26 16:40
@JasonJShuler Ah, sorry to hear about the data loss.  Never fun.  8(
Spriggit is definitely still experimental.  I've got a milestone set up to hopefully wrap up the major items needed to get it to a state that could be called `1.0`
https://github.com/Mutagen-Modding/Spriggit/milestone/1

**Comment by Noggog** [comment] 2024-05-07 19:46
Should be fixed once this gets pulled in
https://github.com/Mutagen-Modding/Mutagen.Bethesda.Serialization/commit/a3e6e00896706c74210877dc4e2d9414c5e4cd7a

**Closed by Noggog** 2024-05-07 19:46 UTC

**Comment by JasonJShuler** [comment] 2024-05-13 16:07
Thank you so much! I apologize for my tone - I'm going through stuff.., I
would never be so pushy in person.

Spriggit is otherwise fabulous - I'm very much looking forward to taking
the leap into using mutagen directly, rather than text editors to make
batch edits and other things. Very exciting project - and I also can't wait
to have a good development pipeline. Thanks again!
